name = "DoseCalculations"
uuid = "b0d14063-c48a-4081-83d5-5a5ab48cb495"
authors = ["lmejn <33491793+lmejn@users.noreply.github.com>"]
version = "0.7.4"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DICOM = "a26e6606-dd52-5f6a-a97f-4f611373d757"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NRRD = "9bb6cfbd-7763-5393-b1b5-1c8e09872146"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
CoordinateTransformations = "0.6"
DICOM = "0.10"
FileIO = "1"
Glob = "1"
HDF5 = "0.16"
Interpolations = "0.14"
JSON = "0.21"
MeshIO = "0.4"
Meshes = "0.28"
NRRD = "0.6"
Optim = "1"
Polyester = "0.7"
ProgressMeter = "1"
Roots = "2"
Rotations = "1"
StaticArrays = "1"
WriteVTK = "1"
julia = "1.8"
